-- Step 1: Ensure you are in the correct container (Pluggable Database)
ALTER SESSION SET CONTAINER=FREEPDB1;

-- Step 2: Create the user in that specific container
CREATE USER njord_user IDENTIFIED BY njord_password QUOTA UNLIMITED ON USERS;

-- Step 3: Grant privileges to the new user
GRANT CONNECT, RESOURCE, CREATE TABLE TO njord_user;

-- Step 4: Commit changes to make sure the user is visible
COMMIT;

CREATE TABLE njord_user.neo (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    neo_id VARCHAR2(255) NOT NULL,
    neo_reference_id VARCHAR2(255),
    name VARCHAR2(255),
    name_limited VARCHAR2(255),
    designation VARCHAR2(255),
    nasa_jpl_url VARCHAR2(255),
    absolute_magnitude_h FLOAT,
    is_potentially_hazardous_asteroid VARCHAR2(8),
    is_sentry_object VARCHAR2(8)
);
